title: Mietzekater
description: Lokale Sharing-Plattform für Nachbarschaftshilfe
baseurl: "" # Empty string for custom domain
url: "https://www.mietzekater.de" # Full URL of your custom domain

# Build settings
permalink: /:categories/:title/
markdown: kramdown

# Blog settings
blog_permalink: /blog/:year/:month/:day/:title/
paginate: 9
paginate_path: "/blog/page:num/"

# Collections
collections:
  categories:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/blog/:title/"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
